### ISSUE TITLE
Compression levels?

### ISSUE THREAD

**Issue by Tigt** [ludovicofischer/metalsmith-gzip#3]
What gzip compression level does this plugin operate at? I tried checking zlib's page for any information, but I'm not sure I found the right one.

If I'm going to be zipping files only once, I might as well gzip at level 9 for a few extra percentages in savings / decode effort.

**Comment by ludovicofischer** [comment]
Release 0.3  has been pushed to npm. Compression levels can be set via the gzip key in the options object . For example: `compress({ gzip: { level: 6 }})`.

**Comment by Tigt** [comment]
![Large files can benefit from 17KB or more on gzip level 9](https://cloud.githubusercontent.com/assets/8072522/5601370/d59b7992-92c8-11e4-9c25-8a0cebffe759.PNG)

Sorry about my tardiness.

As you can probably see from the comparision above, this definitely ended up being worth it for larger files. Thank you so much for your patience and time! I'll have to come back after a few months of learning JS better and see if I can help contribute to something else of yours.

**Comment by ludovicofischer** [comment]
Excellent! I am glad that it works. I try to test it, but without others confirming with their own setups, it’s hard to know whether things work fine.

You’re welcome to try again, although I am not sure I have that many projects to contribute to,
